export const NAME_CHANGED = 'NAME_CHANGE';
export const NAME_VALIDATE = 'NAME_VALIDATE';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const EMAIL_VALIDATE = 'EMAIL_VALIDATE';

export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const PASSWORD_VALIDATE = 'PASSWORD_VALIDATE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUESTED';
export const SIGN_UP_IN_PROGRESS = 'SIGN_UP_IN_PROGRESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';